### ISSUE TITLE
Error when installing 

### ISSUE THREAD

**Issue by tgmueller** [R-ArcGIS/r-bridge#27]
Hi Folks:
I'm using ArcGIS Pro and python.  I'm having problems installing ArcGISBindings 1.0.1.13.2.  The steps I took were as follows:

1. Made a new Python environment in with Manage Environments using Manage Environments in ArcGIS Pro and switched to that new environment.  

2. Opened up the ArcGIS Pro Python command prompt and ran the following command and verified that the new environment was activated.  

3. Then I installed conda specific to that new enviroment: conda install -n env_1 r-essentials.  

4. In windows explorer I confirmed that R base was installed to   "r-base-3.5.1-hac0af64_1"

5. I opened Jupyter Notebook and created a new R notebook but received an error as shown in the top of the screen shot below.  That caused Jupyter notebook to keep restarting as shown in the bottom of the screen shot below.

![2018-11-21 14_22_23-clipboard](https://user-images.githubusercontent.com/9053330/48866640-274df600-ed99-11e8-8101-8df4825f2754.png)

6. Then I went into ArcGIS Pro and Examined my Geoprocessing environments and set the environment to r-base-3.5.1-hac0af64_1.   

![2018-11-21 14_26_42-clipboard](https://user-images.githubusercontent.com/9053330/48866739-814ebb80-ed99-11e8-9be4-3857b54f60b2.png)

7.  When I tried to install the ArcGISPackage I get an error when i try to install.  

![2018-11-21 14_25_32-clipboard](https://user-images.githubusercontent.com/9053330/48866699-5a908500-ed99-11e8-89a0-e2baeae9df49.png)

I've searched this error but can't find anything on it.  Please let me know if you have thoughts.

**Comment by scdub** [comment]
@ tgmueller sorry for a (very!) belated response. I missed this issue when it was first brought up. There are a couple of things:

1. The Geoprocessing options pane isn't smart enough to detect R conda environments -- this will be fixed in a future release of Pro. For now, you can visit the Python backstage, navigate to your environment, and install the `r-arcgisbinding` package if you want to set this up via a conda based R.
2. When these kinds of DLL loads fail, typically that means that is isn't detecting its PATH information correctly. Before you start the notebook, you can check the PATH variable for the correct entries, or can force the activation by running "Python Command Prompt", then running "activate <my_env>", then running `jupyter notebook` from that location.

**Comment by scdub** [comment]
@tgmueller Since you posted, we've released the `r-arcgis-essentials` package, which includes the necessary components to wire up Jupyter R notebooks, Microsoft R open, and other related pieces. Hopefully, that solves this workflow -- we've also made the options pane smarter about finding conda environments. Closing this, but if this is still an issue for you, feel free to reopen.
