### ISSUE TITLE
"arcgisbinding" not available for R 4.1

### ISSUE THREAD

**Issue by chinhqho** [R-ArcGIS/r-bridge#60]
Has newest version of R 4.1.1 broken "arcgisbinding".
When I run this following script using R 32 bit to connect R with ArcGIS Desktop 10.7:
install.packages("arcgisbinding", repos="http://r-arcgis.github.io/r-bridge", type="win.binary")
I got the error, which said:package ‘arcgisbinding’ is not available as a binary package for this version of R

platform i386-w64-mingw32
arch i386
os mingw32
system i386, mingw32
status
major 4
minor 1.1
year 2021
month 08
day 10
svn rev 80725
language R
version.string R version 4.1.1 (2021-08-10)
nickname Kick Things

**Comment by orhuna** [comment]
@chinhqho there are no bugs associated with `arcgisbinding` and R 4.1.1. as per our latest regression tests. The issue here is using `install.packages` with `arcgisbinding` for the 32-bit version of R. Please use the installation [steps here](https://github.com/R-ArcGIS/r-bridge-install). You can also try offline installation tips [here](https://github.com/R-ArcGIS/r-bridge-install#offline-installation).

**Comment by chinhqho** [comment]
@orhuna thanks for looking at this issues. I can confirm that I can install arcgisbinding on the 32 bit version of R4.0.2, 4.0.3 ad 4.1.1 using Rgui and the repos ="https://r.esri.com" `install.packages("arcgisbinding", repos="https://r.esri.com", type="win.binary")`
So it appears there is interaction issues betwen arcgisbinding and RStudio 1.4.1717 which I have opened a new issued.
